spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/mybatis'
    username: root
    password: '123456'
  thymeleaf:
    cache: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl

server:
  port: 9023